spring:
  application:
    name:
      snapload


  main:
    lazy-initialization: true

downloader:
  output-dir:
    "${user.home}/Downloads"
  audio-format: "mp3"
  audio-quality: 0
  embed-thumbnail: true
  add-metadata: true
  filename-template: "%(title)s"
  yt-dlp-command: "yt-dlp"
  ffmpeg-command: "ffmpeg"
  video-quality: 1080

